### ISSUE TITLE
how can try it?

### ISSUE THREAD

**Issue by johnfelipe** [sandyjswl/python-PageRank#1]
how can try it?

**Comment by johnfelipe** [comment]
anyone?

**Comment by Shubh96** [comment]
@johnfelipe  Could you please elaborate what would you exactly want to know? Its implementation or how it works, or how would you get to get the page rank code run?

**Comment by johnfelipe** [comment]
cheatsheet for tryout
Stay alert

**Comment by Shubh96** [comment]
Okay. Got you. I am preparing one and will soon upload it to my github account. May be by tomorrow, i will give you the link once i get that ready.

**Comment by johnfelipe** [comment]
Perfect bro, i will stay alert

**Comment by Shubh96** [comment]
@johnfelipe [Issue #1] Hello friend, as said, i have updated my code into my github repo. The code there is pretty much the same, except it is a little more documented using comments and more of it would be added. Find it here at [Shubh96/pageRank](https://github.com/Shubh96/pageRank) and for you query, read the README given there. It explains the process of execution.

**Comment by Shubh96** [comment]
@johnfelipe did that solve your issue? if yes then please mark it solved and close the issue.
